- omc3/tfs/handler.py
> #24: Column names have no specified type

- omc3/utils/dict_tools.py
Fixes #15 . It does not shorten the traceback, but has all the info in it
> #15: Not really shorter, but sufficiently exact

- omc3/tfs/handler.py
> #17: Added the two validation checks

- .travis.yml
> Travis produces coverage results for codeclimate

- omc3/harpy/frequency.py
> Corrected frequencies interval in lin files

- omc3/harpy/clean.py
- omc3/harpy/handler.py
- omc3/hole_in_one.py
- requirements.txt
- tests/accuracy/test_harpy.py
Obviously, no BPM resynchronisation is possible in such a case
> # 95: Frequency analysis can run without the model

- omc3/utils/logging_tools.py
> #102: Removed logging handlers on logger creation

- omc3/madx_wrapper.py
> #107 : Madx wrapper uses entrypoint

- omc3/harpy/clean.py
- omc3/harpy/handler.py
- omc3/harpy/kicker.py
- omc3/model/accelerators/accelerator.py
- omc3/model/accelerators/lhc.py
- omc3/optics_measurements/beta_from_phase.py
- omc3/optics_measurements/chromatic.py
- omc3/optics_measurements/dpp.py
- omc3/optics_measurements/kick.py
- omc3/optics_measurements/measure_optics.py
- omc3/optics_measurements/phase.py
- omc3/optics_measurements/rdt.py
- omc3/tbt/handler.py
- tests/accuracy/test_harpy.py
- tests/accuracy/test_measure_optics.py
- tests/accuracy/twiss_to_lin.py
- tests/unit/test_tbt.py
> Replaced .values for .to_numpy()

- tests/accuracy/test_harpy.py
- tests/accuracy/twiss_to_lin.py
> Fixed numpy seed and added init to bin directory

- omc3/optics_measurements/phase.py
The change is extremely simply.
Provided you're still ok with it, it should go through without breaking a sweat.
> Refactor(docstring): #187 complete example matrix

- omc3/tbt_converter.py
- tests/accuracy/twiss_to_lin.py
- tests/unit/test_tbt.py
- tests/unit/test_tune_analysis.py
adding noise levels from cmdline would not work due to casting error
now cast to float to avoid issue, test for tbt_converter adding noise added
Fixes #192
> BugFix/192/broken noise levels in tbt_converter

- omc3/optics_measurements/beta_from_phase.py
corrected parameter values
explicitly filtered out negative betas and too high errors
> # Fixes #200:

- omc3/kmod/analysis.py
- omc3/run_kmod.py
- tests/accuracy/test_kmod.py
previous accuracy for ideal simulation was put to 1%, now reduced to show real accuracy
> tweaking test settings for kmod to show accuracy

- omc3/utils/iotools.py
> #205 fix of indent

- omc3/harpy/frequency.py
- tests/accuracy/test_harpy.py
also changing some .values to .to_numpy()
> FIxes #210: aligned longitudinal phase to correct reference turn

- omc3/optics_measurements/dispersion.py
- omc3/optics_measurements/measure_optics.py
Prepares codes for newer version of pandas (>=1.0.0).
> Fixes #213: Changed the .loc with potentially missing labels

- omc3/tbt/reader_lhc.py
- omc3/utils/time_tools.py
- setup.py
- tests/unit/test_time_tools.py
> Get rid of pytz everywhere

- .github/workflows/coverage.yml
- setup.cfg
> #253 setup.cfg: moved pytest coverage arguments to github action

- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/publish.yml
> Move python version for non cron workflows

- omc3/plotting/plot_tfs.py
- tests/unit/test_plot_tfs.py
> plot_tfs: No output accepted

- omc3/model/accelerators/accelerator.py
- omc3/model/accelerators/lhc.py
This is a fix for #293 
The error was a typo when creating the list of absent modifiers.
Fix changes are line 175-186 of ` omc3/model/accelerators/lhc.py ` in this branch.
Other changes are formatting and type hints.
> No modifiers error message fix

- omc3/correction/response_madx.py
Paths now relative in madx-script as we switch to model-dir in madx-run anyway.
Fixes #310.
> Change to relative paths

- omc3/optics_measurements/coupling.py
Index intersection introduced in #312 was not propagated properly to output dataframe
> fix scrambled index

- omc3/model/accelerators/lhc.py
- omc3/model/model_creators/lhc_model_creator.py
> Modelcreation for beamtest

- omc3/scripts/betabeatsrc_output_converter.py
- tests/unit/test_betabeatsrc_output_converter.py
> Converter coupling files renaming fix

- omc3/madx_wrapper.py
> Fix NoneTypes for Path in madx_wrapper

- CHANGELOG.md
- omc3/__init__.py
Version update and changelog content for a patch release with the new LHC Run 3 knobs
> Release 0.2.5

- CHANGELOG.md
- README.md
- doc/entrypoints/scripts.rst
- omc3/__init__.py
- omc3/definitions/formats.py
- omc3/harpy/frequency.py
- omc3/scripts/linefile_clean.py
- omc3/scripts/linfile_clean.py
- omc3/utils/outliers.py
- tests/unit/test_linfile_clean.py
Adds a script to clean columns from linfiles (or any tfs files, actually) via the `outliers.get_filter_mask` function.
> Quick clean

- omc3/correction/handler.py
I am not sure if this would have actually caused any problems, but better to initialize it this way.
Might have lead to rounding errors.
> Initialize dataframe with float instead of int

- CHANGELOG.md
- omc3/__init__.py
- omc3/tbt_converter.py
Adds the option to choose an output tbt datatype for the converter
> Added tbt output datatype

- CHANGELOG.md
- omc3/__init__.py
- omc3/optics_measurements/coupling.py
If the phase matrix is filtered, both rows **and** columns have to be filtered.
> [Bugfix] fix phase filtering

- CHANGELOG.md
- omc3/__init__.py
- omc3/scripts/create_logbook_entry.py
- omc3/utils/iotools.py
- omc3/utils/rbac-krb5.conf
- omc3/utils/rbac.py
- setup.py
- tests/conftest.py
- tests/unit/test_create_logbook_entry.py
- tests/unit/test_rbac.py
New python functions to create logbook entries and to get an rbac token.
> Logbook wrapper

- MANIFEST.in
- doc/_static/css/custom.css
- doc/_templates/layout.html
- doc/conf.py
- omc3/optics_measurements/beta_from_phase.py
- omc3/optics_measurements/phase.py
- omc3/plotting/plot_optics_measurements.py
- omc3/utils/iotools.py
Fixes:
- OptionalString: 'None' as input is converted to None
- Missing Kerberos config added to MANIFEST for packaging, fixes #420 
- Plot Optics plots now correct error-column, e.g. for beta-beating, fixes #418 
- Added warnings/errors for too few bpms in N-BPM/3-BPM methods. fixes #361 
- Added navbar to sphinx documentation, fixes last point in #407
> Minor bugfixes june 2023

- CHANGELOG.md
- omc3/__init__.py
- omc3/plotting/utils/windows.py
- tests/unit/test_plot_windows.py
I wrote some tests for this, but missed that the file was not added to git. No one noticed, but that explains why the coverage was so low.
> Missing Plotting Windows Tests

- CHANGELOG.md
- omc3/__init__.py
- omc3/optics_measurements/beta_from_phase.py
Andreas remembered the quick fix for the large errors found in the first and last bpms for the 3-bpm method.
> Fix for larger errorst in first/last bpms (thx Andreas)

- CHANGELOG.md
- omc3/__init__.py
- omc3/scripts/kmod_import.py
I noticed that the filter patter was wrong. While it was working for the k-mod files that Felix provided, the real-life ones might have much more elements in the IR region as entries.
Also a bit more logging, as this was very sparse.
> Fix K-Mod importer

- CHANGELOG.md
- omc3/__init__.py
- omc3/optics_measurements/constants.py
- omc3/scripts/kmod_lumi_imbalance.py
- tests/inputs/kmod/references/effective_betas_beta0.22m0.22m.tfs
- tests/inputs/kmod/references/effective_betas_ip1_ip5_beta0.22m0.22m.tfs
- tests/unit/test_kmod_importer.py
- tests/unit/test_kmod_lumi_imbalance.py
> Kmod lumi imablance: IP Naming
