- .gitignore
vim creates a tags file for syntax highlighting. we want to ignore it
> add 'tags' to .gitignore

- omc3/definitions/formats.py
- omc3/harpy/handler.py
- omc3/hole_in_one.py
- omc3/model/accelerators/accelerator.py
- omc3/model/accelerators/esrf.py
- omc3/model/accelerators/lhc.py
- omc3/optics_measurements/constants.py
- omc3/optics_measurements/kick.py
- tests/accuracy/twiss_to_lin.py
* Refactored kick.py to use only constants as Column names
* harpy/handler.py: added TIME to headers.
* accelerator.py: refactored strings of element types to AccElementTypes class
> #73 Add Kicktime to kick_$.tfs

- README.md
- setup.py
* Changed dependency layout
* added 'all'
* some pytest-args examples
Controversial:
* added pillow-requirement as old version kept crashing with matplotlib (https://github.com/matplotlib/matplotlib/issues/14263 )
> #181 Easier dependency management

- omc3/utils/time_tools.py
- tests/unit/test_time_tools.py
Fixes #226 
dateutil.tz works a bit differently than pytz, the `localize` function for instance can't be used anymore.
All datetimes are here zone-aware and one change to be noted is that a AccDatetime object can now be created directly with a `tzinfo` instead of using the `.local` property on it.
`dt.astimezone` returns a new object, so does `dt.replace`, we would always get a AccDatetime object in UTC.
> Use dateutil instead of pytz

- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
Should fix the `set-env` use in the `coverage` workflow.
Hopefully fix the warning in the `documentation` workflow by updating the used version of the `github-pages-deploy-action`.
Need to open this PR to trigger the first one.
> Fix set-env use

- README.md
- doc/modules/utils.rst
- omc3/amplitude_detuning_analysis.py
- omc3/tune_analysis/timber_extract.py
- omc3/utils/mock.py
- setup.cfg
- setup.py
- tests/unit/test_mock.py
This is the implementation PR for https://github.com/pylhc/omc3/issues/272
Checklist:
I took the opportunity to remove unsused parts of `setup.py` and do a little bit of type hinting in `omc3.tune_analysis.timber_extract.py`.
I also named the extra `tech` to stay consistent with the naming adopted in `PyLHC`.
> Tech dependency for pytimber

- .github/workflows/coverage.yml
- .github/workflows/cron.yml
- .github/workflows/documentation.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
These changes include `pip`'s out-of-directory cache in the github actions caching step, which will speed up the `Install package` step.
Previous implementation was my bad.
> Fix cache step in workflows

- .github/workflows/README.md
- .github/workflows/cron.yml
- .github/workflows/tests.yml
As discussed previously, since Ubuntu 16.04 reached end of LTS we will remove it from CI workflows This will please @JoschD :)
I will create similar PRs on other repos when appropriate.
NB: we will need to update the `master` branch protection rules / requirements before merging.
> Removing Ubuntu 16.04 from CI

- omc3/tbt/handler.py
- omc3/tbt_converter.py
This is a workaround for #288 
This PR introduces a `--drop_elements` flag to the `tbt_converter`, which will drop said elements in the `TbtData.matrices` after loading.
The only reasons to have elements mismatch like in #288 would be to either have a wrong model, or to have additionnal elements from simulation tracking (see [this comment](https://github.com/pylhc/omc3/issues/288#issuecomment-870646395)). In the second case, this is a valid solution. In any case, it doesn't hurt to have the option in `tbt_converter`.
> Add element dropping option for the tbt_converter

- omc3/tbt/handler.py
- omc3/tbt/reader_esrf.py
- omc3/tbt/reader_iota.py
- omc3/tbt/reader_lhc.py
- omc3/tbt/reader_ptc.py
- omc3/tbt/reader_trackone.py
- omc3/tbt_converter.py
- tests/unit/test_tbt.py
This PR is complementary to #290.
- It adds tests for the `--drop_element` flag, asserting elements are properly dropped and that a warning is properly logged if elements are not found.
- It makes the conversion to `pathlib` for all `tbt`-related functionality: `tbt_converter` and all members of `tbt` now also accept `pathlib.Path` objects.
> Pathlib for tbt functionality and tests for --drop_elements

- omc3/madx_wrapper.py
- omc3/model/model_creators/abstract_model_creator.py
- omc3/model/model_creators/lhc_model_creator.py
- omc3/model/model_creators/ps_model_creator.py
- omc3/model/model_creators/psbooster_model_creator.py
- omc3/model_creator.py
- omc3/plotting/utils/colors.py
- tests/conftest.py
- tests/unit/test_model_creator.py
This is a fix for #302 
In `madx_wrapper`, using absolute paths to call the jobfile and `MAD-X` executable ensures the file is found regardless of having `cwd`-ed into the `outputdir`.
> Model Creator Fix

- .github/workflows/documentation.yml
This is similar to a change I made in https://github.com/pylhc/pylhc.github.io/pull/48
The documentation will now also build on `pull_request` events and if successful, the build will be uploaded as artifacts so that reviewers can easily check the state of the documentation without building it locally.
> Upload documentation artifacts for PR events

- omc3/optics_measurements/coupling.py
In case that input files have more observation points than defined in the model, an additional intersection is needed.
> added intersection between input files and phase_x/phase_y

- omc3/model/accelerators/ps.py
- omc3/model/accelerators/psbooster.py
- setup.py
- tests/unit/test_model_creator.py
A wrongly implemented fix for #284 for the PS and PSBooster prohibited creating models without excitation for these machines.
> Fix PS and PSBooster Driven Tunes

- omc3/model/model_creators/lhc_model_creator.py
Before it was trying to unlink if it was there but now it skips the linking if the folder is already there. This enables the creation of model if you have manually copied or checked out the repository.
> To enable model creation for 2022 if no afs is available.

- omc3/optics_measurements/rdt.py
Before, when using a single file, the error on the RDT amplitude would be inf.
Now, if the fitting returns an infinite errors, it is replaced with 0..
> Fix Amplitude error for RDT when using one file

- omc3/model/accelerators/lhc/systematic_errors/6800GeV.tfs
as the title says.
the values are exactly the same as 6500GeV, our best guess so far
> add 6800GeV to lhc uncertainties

- CHANGELOG.md
- omc3/__init__.py
- omc3/optics_measurements/coupling.py
the merge (`pandas.merge` command, not this git merge) performed intersection of `NAME` **and** `S`, removing many BPMs where horizontal and vertical `S` wasn't the same.
fix: remove the intersection along `S`
> remove S intersection while merging in coupling

- CHANGELOG.md
- omc3/__init__.py
- omc3/hole_in_one.py
- omc3/optics_measurements/coupling.py
and another one...
this pull request adds an option `coupling_pairing` which adds the ability to control how the coupling module selects the BPMs for the 2 BPM method
0: select best candidate (approx pi/2 model phase advance)
>= 1: take n-th following BPM
> add coupling pairing option

- omc3/plotting/plot_amplitude_detuning.py
- omc3/plotting/plot_bbq.py
- omc3/plotting/plot_spectrum.py
- omc3/plotting/plot_tfs.py
- omc3/plotting/spectrum/stem.py
- omc3/plotting/spectrum/utils.py
- omc3/plotting/spectrum/waterfall.py
- omc3/plotting/styles/amplitude_detuning.mplstyle
- omc3/plotting/styles/bbq.mplstyle
- omc3/plotting/styles/spectrum.mplstyle
- omc3/plotting/styles/standard.mplstyle
- omc3/plotting/utils/annotations.py
- omc3/plotting/utils/style.py
- omc3/utils/iotools.py
removes all tight_layout() calls and tries to handle all plotting styles via rcParams.
Input for all plotting functions should allow for `plot_styles` and `manual_style`, where the former is a list of omc3-styles or paths to your own styles and manual style is a dictionary (which allows for more python shenanigans than .mplstyle files) with additions to the styles.
> Plotting style improvements

- CHANGELOG.md
- omc3/__init__.py
- omc3/model/accelerators/lhc.py
- omc3/model/madx_macros/lhc.macros.run3.madx
- tests/unit/test_model_creator.py
Currently the LHC model creator will call ats macros (tune matching for instance) only if the year is exactly "2018". Similarly, it calls the run3 macros file only if the year is exactly "2022".
This quick change checks that the year is `>=` to these values (with `int` conversion) and not strictly equal.
It also corrects the run 3 macros to use the proper knobs (`op` or `sq` depending on optics).
I have updated the version number to make this a patch release.
> LHC macros call fix

- omc3/__init__.py
- omc3/knob_extractor.py
This cleans up the logging of knob extractor by suppressing pytimber logs and printing only one statement for missing knob values.
> cleaned logging

- CHANGELOG.md
- omc3/__init__.py
- omc3/correction/handler.py
- omc3/global_correction.py
- omc3/model/accelerators/lhc.py
- omc3/scripts/fake_measurement_from_model.py
Fullresponse Path was not converted to Path() instance. Fixed
> Minor fixes in fake measurement, full response and corrections

- CHANGELOG.md
- omc3/__init__.py
- omc3/plotting/plot_amplitude_detuning.py
- omc3/tune_analysis/constants.py
- omc3/tune_analysis/fitting_tools.py
- omc3/tune_analysis/kick_file_modifiers.py
- tests/unit/test_tune_analysis.py
a) Second order fits are not done properly in the polyfit function. This fixes it.
b) Detuning fits were always plotted with and without BBQ correction. A new parameter can now be given choosing either one (or both, as is default)
> Amplitude Detuning: Proper handling of second order fits

- .github/workflows/README.md
- .github/workflows/coverage.yml
- .github/workflows/cron.yml
- .github/workflows/documentation.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- doc/entrypoints/analysis.rst
- doc/entrypoints/correction.rst
- doc/entrypoints/other.rst
- doc/entrypoints/plotting.rst
- doc/entrypoints/scripts.rst
- doc/modules/correction.rst
- doc/modules/definitions.rst
- doc/modules/harpy.rst
- doc/modules/kmod.rst
- doc/modules/model.rst
- doc/modules/optics_measurements.rst
- doc/modules/plotting.rst
- doc/modules/tune_analysis.rst
- doc/modules/utils.rst
- setup.py
While looking at the workflows in #416 I realized we were still using the deprecated `set-output` in this repo (which is not needed anymore) and had an inconsistency in the `basic` and `extended` tests steps.
Edit: also fixes the over-indexing in the docs.
No code change in this PR.
> Workflows and doc fixes

- omc3/optics_measurements/dpp.py
The pandas Series has to be converted to a numpy array for the indexing to work.
Functionality has been removed after depreciation and leads to an error.
Somehow the change has already been made for the function `calculate_dpoverp` with the ~same code at line 76
> Fix pandas indexing error

- omc3/__init__.py
- omc3/scripts/betabeatsrc_output_converter.py
Closes #435.
Fix is simply to divide by 1e3 when doing the conversion to go from the `mm` of BBsrc to the `m` of omc3.
> Fix CO units issue in BBsrc converter

- CHANGELOG.md
- omc3/__init__.py
- omc3/correction/response_madx.py
- omc3/knob_extractor.py
- omc3/model/accelerators/lhc.py
- omc3/model/constants.py
- omc3/model/model_creators/abstract_model_creator.py
- omc3/model/model_creators/lhc_model_creator.py
- omc3/model/model_creators/ps_base_model_creator.py
- omc3/model_creator.py
- omc3/response_creator.py
- omc3/utils/iotools.py
- setup.py
- tests/unit/test_model_creator.py
Instead of having the `knobs.madx` hard-coded they will be given as modifiers from the GUI.
This avoids having to create empty `knobs.madx` file beforehand, whenever you want to create a model.
This PR also cleans up a few more things from the model creation:
- remove the `corrections.madx` from best-knowledge model, as we never used this. 
If needed in the future, this can also be simply given as a modifier.
- Zip the mad-x output log-file from the response model creation. As this runs in parallel by default, using the number of available cores, the final (merged) log file can be quite big, even with the sequence loading not echoed.
- Also response creation: keep the 0th job-file as reference in the model directory, so that one can check that the setup of the machine is correctly …
> Use modifiers for knobs madx

- CHANGELOG.md
- omc3/__init__.py
- omc3/harpy/frequency.py
- omc3/harpy/handler.py
- omc3/model/madx_macros/general.macros.madx
- omc3/optics_measurements/beta_from_phase.py
- omc3/optics_measurements/kick.py
- omc3/optics_measurements/phase.py
- omc3/optics_measurements/rdt.py
- omc3/tune_analysis/bbq_tools.py
- pyproject.toml
- tests/unit/test_model_creator.py
- tests/unit/test_rdt_magnet_order.py
- Adds DOROS BPMs to twiss.dat
- Removes Pandas future warnings, as far as I saw them:
- `phase.py`: `FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated.`
- `beta_from_phase.py` and `kick.py`: `FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas.`
> madx pattern for doros BPMs

- CHANGELOG.md
- omc3/__init__.py
- omc3/knob_extractor.py
While we removed `/mcr/bin` from the lhcop `PATH`, which allows us to run the knob-creator in the CCC terminals,
it is still added when starting the CCM (see https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3768823 ). 
This PR provides a hack to remove it again ...
> Fix knob extractor

- CHANGELOG.md
- omc3/__init__.py
- omc3/knob_extractor.py
This fixes
```
15:43:43 - omc3.knob_extractor STDERR: Traceback (most recent call last):
15:43:43 - omc3.knob_extractor STDERR:   File "/afs/cern.ch/eng/sl/lintrack/omc_acc_py/base/2021.12/lib/python3.9/runpy.py", line 197, in _run_module_as_main
15:43:43 - omc3.knob_extractor STDERR:     return _run_code(code, main_globals, None,
15:43:43 - omc3.knob_extractor STDERR:   File "/afs/cern.ch/eng/sl/lintrack/omc_acc_py/base/2021.12/lib/python3.9/runpy.py", line 87, in _run_code
15:43:43 - omc3.knob_extractor STDERR:     exec(code, run_globals)
15:43:43 - omc3.knob_extractor STDERR:   File "/afs/cern.ch/eng/sl/lintrack/omc_python3/lib/python3.9/site-packages/omc3/knob_extractor.py", line 633, in <module>
15:43:43 - omc3.knob_extractor STDERR:     main()
15:43:43 - omc3.knob_extractor STDERR: …
```
> Knob extractor spark props

- CHANGELOG.md
- omc3/__init__.py
- omc3/optics_measurements/iforest.py
- omc3/scripts/bad_bpms_summary.py
- tests/unit/test_bad_bpms_summary.py
Looks now like
```
INFO | Bad BPMs Summary. Hint: '[BPM]' were filtered as known bad BPMs. | scripts.bad_bpms_summary
INFO | Highest bad BPMs of LHCB1 from HARPY:
BPM          X                   Y           Reasons
BPM.11R4.B1  100.0% (18/18)      100.0% (18/18)      EXACT_ZERO | FLAT
BPM.29L6.B1  100.0% (18/18)              -           EXACT_ZERO
BPM.8L1.B1  100.0% (18/18)              -           EXACT_ZERO | FLAT
BPMSX.4L8.B1  100.0% (18/18)              -           SPIKY
BPMSE.4L6.B1  100.0% (18/18)              -           SPIKY
BPMSX.7R1.B1  100.0% (18/18)      100.0% (18/18)      EXACT_ZERO | FLAT
BPM.18R2.B1          -            55.6% (10/18)      EXACT_ZERO | scripts.bad_bpms_summary
```
> Add bad bpms reasons

- CHANGELOG.md
- omc3/__init__.py
- omc3/utils/time_tools.py
- pyproject.toml
- tests/unit/test_time_tools.py
Cron jobs have picked up that the `.local` property of our `AccDateTime` raises issues as it tries to do some non-`tzinfo` inherited comparisons.
As far as I could tell this is mostly an annoyance due to subclassing the `datetime` class. A very simple fix is to simply cast to datetime first (using our own `.datetime` property) and then ask for `.astimezone` as previously).
PR is a bit more than that since I took the opportunity of dropping Python 3.9 support for this release (as we did with `tfs-pandas`) and solve the mess of `pytables` and `numpy 2.x` dependencies.
> Fix datetime errors in latest Python

- pyproject.toml
Simply having `QtPy` is not enough as a binding itself is needed.
> Add qt5 binding depencendy

- CHANGELOG.md
- omc3/scripts/bad_bpms_summary.py
Added the NaNs (see https://github.com/pylhc/omc3/tree/0.21.0 ) as a known filter/reason to the summary.
> Bad BPMs Summary: NaNs

- pyproject.toml
The default import mode in `pytest` is set to `prepend`, which is a historical thing that they don't recommend.
In their [documentation](https://docs.pytest.org/en/stable/explanation/goodpractices.html#choosing-an-import-mode) it is recommended to use `--import-mode=importlib `. It was also hinted in our minimum pytest version that this new mode was the one with no drawbacks, see 7.0.x docs [here](https://docs.pytest.org/en/7.0.x/explanation/goodpractices.html#choosing-a-test-layout-import-rules) and [here](https://docs.pytest.org/en/7.0.x/explanation/pythonpath.html#import-modes).
This should not have an impact on the tests themselves but let's see if the CI is fine with it.
> Maintenance - Set `pytest `import mode

- .git-blame-ignore-revs
- omc3/correction/response_io.py
- omc3/model/accelerators/accelerator.py
- omc3/model/accelerators/lhc.py
- omc3/model_creator.py
- omc3/plotting/plot_spectrum.py
- omc3/plotting/plot_tfs.py
- omc3/plotting/spectrum/stem.py
- omc3/plotting/spectrum/utils.py
- omc3/plotting/spectrum/waterfall.py
- omc3/plotting/utils/annotations.py
- omc3/plotting/utils/colors.py
- omc3/plotting/utils/lines.py
- omc3/plotting/utils/style.py
- omc3/plotting/utils/windows.py
- omc3/scripts/create_logbook_entry.py
- omc3/scripts/fake_measurement_from_model.py
- omc3/utils/parsertools.py
- pyproject.toml
- tests/accuracy/test_sbs.py
Now that we have a linting check in CI, I am suggesting adding some more rules to the `Ruff` setup on top of the default ones.
This PR introduces a list of rules, some of which I've activated and fixed (hence the file changes). All other changes in said files are the removal of trailing spaces that my IDE did.
~~There was one non-straightforward case of `NPY002` in `omc3/scripts/fake_measurement_from_model.py`, where a `np.random.seed` was set without random number generation, most likely to propagate to all called functions.~~
~~Considering the [numpy docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html) actively discourage doing this, and recommend a per-generator seeding I have propagated the seed down to called functions and let those use it when …
> Tightening the screws, part 1

- .git-blame-ignore-revs
- README.md
Adding the previous master commit's hash to `.git-blame-ignore-revs` and removing the code climate badges from `README.md`.
> Adding Linting Commit to Git-Rev File and Removing CodeClimate Badges
